<?php $this->assets->outputCss(); ?>
<div class="w-screen h-screen p-2 bg-gray-200">
    <form action="/" method="post" class="flex">
        <input type="text" value="<?php echo isset($query) ? $query : "facts" ?>" name="search" placeholder="search books here..." class="placeholder:italic rounded-sm focus:shadow w-full" required>
        <input type="submit" value="search" class="bg-indigo-500 text-white p-2 rounded-sm ml-2 shadow">
    </form>
    <div class="details grid grid-cols-12 p-2 bg-white rounded-sm shadow m-3">
        <div class="first p-3 col-span-4 border-r flex justify-center items-center flex-col">
            <img src="<?php echo $image; ?>" class="hover:shadow-2xl hover:shadow-indigo-400 hover:my-5 border rounded-lg shadow-lg" alt="" style="width:200px;height:300px;">
            <button class="mt-3 w-64 text-white bg-indigo-500 p-2 rounded-sm w-full shadow"><i class="fa fa-book"></i> want to read</button>
            <span class="my-2"></span>
            <button class="w-64 text-white bg-indigo-800 p-2 rounded-sm w-full shadow"><i class="fa fa-trash"></i> want to throw</button>
            <div class="stars flex text-xl p-2">
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
            </div>
        </div>
        <div class="second col-span-8 p-2 text-gray-700">
            <i class="text-lg text-gray-600">An edition of <span class="underline"><?php echo $data["details"]["publishers"][0]; ?></span></i>
            <p class="text-4xl font-black"><?php echo $data["details"]["title"]; ?></p>
            <p>by <span class="text-indigo-500"><?php
                                                if (isset($data["details"]["authors"])) {
                                                    foreach ($data["details"]["authors"] as $arr) {
                                                        echo $arr["name"];
                                                    }
                                                } else {
                                                    echo "punit";
                                                }
                                                ?></span></p>
            <div class="stars flex items-center">
                <i class="fa fa-star text-indigo-500 hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star text-indigo-500 hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star text-indigo-500 hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
                <i class="fa fa-star hover:text-indigo-500 mr-1"></i>
            </div>
            <div class="tile-long flex justify-between items-center p-3  bg-gray-200 mt-2">
                <div class="flex flex-col justify-center items-center">
                    <p class="font-medium">Publish Date</p>
                    <p class="text-sm text-gray-700"><?php echo isset($data["details"]["publish_date"]) ? $data["details"]["publish_date"] : "N/A"; ?></p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <p class="font-medium">Publisher</p>
                    <p class="text-sm text-gray-700"><?php
                                                        foreach ($data["details"]["publishers"] as $pub) {
                                                            echo $pub;
                                                        }
                                                        ?></p>
                </div>
                <div class="flex flex-col justify-center items-center">
                    <p class="font-medium">Pages</p>
                    <p class="text-sm text-gray-700"><?php echo isset($data["details"]["number_of_pages"]) ? $data["details"]["number_of_pages"] : "N/A"; ?></p>
                </div>
            </div>
            <p class="p-2">
                The main character of Fantastic Mr. Fox is an extremely clever anthropomorphized fox named Mr. Fox. He lives with his wife and four little foxes. In order to feed his family, he steals food from the cruel, brutish farmers named Boggis, Bunce, and Bean every night.
            </p>
            <div class="border-b">
                <?php
                if (isset($data["details"]["subjects"])) {
                ?>
                    <p>subjects</p>
                    <ul class="subjects p-2 text-pink-500 italic">
                        <?php
                        foreach ($data["details"]["subjects"] as $sub) {
                        ?>
                            <li><?php echo $sub; ?></li>
                        <?php
                        }
                        ?>
                    </ul>
                <?php
                }
                ?>
            </div>
            <div class="m-3 flex">
                <a href="<?php echo "https://www.google.co.in/books/edition/" . implode("_", explode(" ", $data["details"]["title"])) . "/" . explode("/", $data["info_url"])[4] . "?hl=en"; ?>" class="buttons bg-indigo-500 text-white p-2 rounded-sm shadow-sm max-w-fit">
                    open in Google
                </a>
                <a href="<?php echo "https://www.google.co.in/books/edition/Slow_reading/F8W5wAEACAAJ?hl=en"; ?>" class="ml-2 buttons bg-indigo-500 text-white p-2 rounded-sm shadow-sm max-w-fit">
                    open in AudioBook
                </a>
            </div>
        </div>
    </div>
</div>